# Site wide configuration

title:            //For The Love Of Code
locale:           en_US
url:              http://Raathigesh.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Raathigeshan
  avatar: bio-photo.jpg
  bio: "I Code Stuff"
  email:
  disqus-shortname: raathigesh
  twitter: Raathigeshan
  facebook: raathigesh
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Raathigesh
  stackoverflow: 902316/raathigeshgi
  linkedin: pub/kugarajan-raathigeshan/23/791/420
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
